project:
  type: book

book:
  title: "Land-Atmosphere Interactions: Praticals"
  author: 
    name: Olivier Bonte
    affiliation: Ghent University
    email: olivier.bonte@ugent.be
  date: "2042-11-5"
  chapters:
    - index.qmd
    - practical_1.qmd
    #- summary.qmd
    - references.qmd
  downloads: [pdf]

bibliography: references.bib
jupyter: python3

format:
  html:
    theme: cosmo
    code-overflow: wrap
    code-fold: show
  pdf:
    documentclass: scrreprt
    include-in-header: 
      text: |
        \usepackage{fvextra}
        \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}

# Allows caching of notebooks when previewing 
execute:
  cache: true


