project:
  type: book

book:
  title: "Land-Atmosphere Interactions: Praticals"
  author: 
    name: Olivier Bonte
    affiliation: Ghent University
    email: olivier.bonte@ugent.be
  date: "2042-10-15"
  chapters:
    - index.qmd
    - practical_1.qmd
    #- summary.qmd
    - references.qmd
  downloads: [pdf]

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt




