project:
  type: book

book:
  title: "Land-Atmosphere Interactions: Practicals"
  subtitle: "Academic year: 2025 - 2026"
  edition: "Academic year test"
  author: 
    name: Olivier Bonte
    affiliation: Ghent University
    email: olivier.bonte@ugent.be
  date: today
  chapters:
    - index.qmd
    - practical_1.qmd
    - practical_2.qmd
    - references.qmd
  downloads: [pdf]
  repo-url: https://github.com/olivierbonte/Land_Atmosphere_interactions_notes_public
  navbar: 
    title: "Land-Atmosphere Interactions: Practicals"
    search: true 
    logo: "figures/logo_H-CEL_no_background.svg"

bibliography: references.bib
jupyter: python3

format:
  html:
    theme: cosmo
    code-overflow: wrap
    code-fold: show
  pdf:
    documentclass: scrreprt
    include-in-header: 
      text: |
        \usepackage{fvextra}
        \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
        \titlehead{%
          \includegraphics[height=3cm]{figures/logo_UGent_EN_RGB_2400_color.png}%
          \hfill%
          \includegraphics[height=3cm]{figures/icon_UGent_BW_EN_RGB_2400_color.png}%
        }
        
# Allows caching of notebooks when previewing 
execute:
  cache: true
  freeze: auto


